name: CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取
        uses: actions/checkout@v7

      - name: 打包
        run: |
          rm -rf .git .github
          # 未匹配到目录时 */ 会直接变成字面量输入, 以下配置可使 */ 解析为空列表
          shopt -s nullglob
          for dir in */; do
            dir_name="${dir%/}"
            echo "Packing ${dir_name}.tar.gz"
            tar -zcf "${dir_name}.tar.gz" "${dir_name}"
          done

      - name: 发布
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ./*.tar.gz
            ./deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
